import type { Metadata } from "next";
import { Cormorant_Garamond, Manrope } from "next/font/google";
import { headers } from "next/headers";
import { AnalyticsConsent } from "@/components/analytics-consent";
import { AnalyticsClickTracker } from "@/components/analytics-click-tracker";
import { ApprovedLocalBusinessStructuredData } from "@/components/approved-business-location";
import { BookServicePopup } from "@/components/book-service-popup";
import { MobileCtaBar } from "@/components/mobile-cta-bar";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { getActiveCatalogSnapshot } from "@/lib/catalog/runtime";
import { brandIdentity, siteMeta } from "@/lib/content";
import { getActivePublicOffers } from "@/lib/offers/public";
import "./globals.css";

const nonIndexDeployment =
  process.env.CATALOG_STAGING_PREVIEW_ENABLED === "true" ||
  process.env.AUDIOSEN_STAGING_DEPLOYMENT === "true";

const sans = Manrope({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const display = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  applicationName: brandIdentity.shortName,
  authors: [{ name: brandIdentity.organizationName, url: "https://audiosen.com/about" }],
  creator: brandIdentity.organizationName,
  publisher: brandIdentity.organizationName,
  category: "health",
  manifest: "/manifest.webmanifest",
  title: siteMeta.title,
  description: siteMeta.description,
  keywords: siteMeta.keywords,
  metadataBase: new URL(siteMeta.canonicalUrl),
  robots: {
    index: !nonIndexDeployment,
    follow: !nonIndexDeployment,
    googleBot: {
      index: !nonIndexDeployment,
      follow: !nonIndexDeployment,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    title: siteMeta.title,
    description: siteMeta.description,
    url: siteMeta.canonicalUrl,
    siteName: brandIdentity.shortName,
    type: "website",
    locale: "en_IN",
    images: [
      {
        url: "/og-image-v2.webp",
        width: 1200,
        height: 630,
        alt: `${brandIdentity.shortName} hearing aids and hearing care across India`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteMeta.title,
    description: siteMeta.description,
    images: ["/og-image-v2.webp"],
  },
  icons: {
    icon: [
      { url: "/favicon-v2.ico", type: "image/x-icon" },
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-48.png", sizes: "48x48", type: "image/png" },
    ],
    shortcut: "/favicon-v2.ico",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // A request-scoped CSP nonce cannot be paired with prerendered HTML. Reading
  // the request headers opts the tree into dynamic rendering so Next applies
  // the nonce generated by proxy.ts to this exact response's scripts.
  await headers();
  const [catalogSnapshot, activeOffers] = await Promise.all([
    getActiveCatalogSnapshot(),
    getActivePublicOffers(),
  ]);
  const catalogSurfaceEnabled = Boolean(catalogSnapshot);
  const offerSurfaceEnabled = activeOffers.length > 0;
  const trialSurfaceEnabled = activeOffers.some(
    (offer) => offer.slug === "hearing-aid-trial",
  );
  return (
    <html lang="en-IN" data-scroll-behavior="smooth">
      <body className={`${sans.variable} ${display.variable} min-h-screen pb-20 font-sans text-slate-900 antialiased md:pb-0`}>
        <ApprovedLocalBusinessStructuredData />
        <a href="#page-content" className="skip-link">
          Skip to main content
        </a>
        {nonIndexDeployment ? null : <AnalyticsConsent />}
        {nonIndexDeployment ? null : <AnalyticsClickTracker />}
        <div className="relative isolate overflow-hidden">
          <div className="pointer-events-none absolute -top-40 left-1/2 h-[34rem] w-[44rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,rgba(9,92,153,0.2),transparent_70%)] blur-2xl" />
          <div className="pointer-events-none absolute right-[-12rem] top-1/3 h-[28rem] w-[28rem] rounded-full bg-[radial-gradient(circle,rgba(14,138,143,0.16),transparent_72%)] blur-3xl" />
          <SiteHeader
            catalogSurfaceEnabled={catalogSurfaceEnabled}
            offerSurfaceEnabled={offerSurfaceEnabled}
            trialSurfaceEnabled={trialSurfaceEnabled}
          />
          <div id="page-content" tabIndex={-1}>
            {children}
          </div>
          <SiteFooter
            catalogSurfaceEnabled={catalogSurfaceEnabled}
            offerSurfaceEnabled={offerSurfaceEnabled}
          />
        </div>
        <BookServicePopup />
        <MobileCtaBar />
      </body>
    </html>
  );
}
